name: kengooroo_ui
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  pinput: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Unbounded
      fonts:
        - asset: lib/fonts/unbounded/Unbounded-ExtraLight.ttf
          weight: 200
        - asset: lib/fonts/unbounded/Unbounded-Light.ttf
          weight: 300
        - asset: lib/fonts/unbounded/Unbounded-Regular.ttf
          weight: 400
        - asset: lib/fonts/unbounded/Unbounded-Medium.ttf
          weight: 500
        - asset: lib/fonts/unbounded/Unbounded-SemiBold.ttf
          weight: 600
        - asset: lib/fonts/unbounded/Unbounded-Bold.ttf
          weight: 700
        - asset: lib/fonts/unbounded/Unbounded-ExtraBold.ttf
          weight: 800
        - asset: lib/fonts/unbounded/Unbounded-Black.ttf
          weight: 900

    - family: TildaSans
      fonts:
        - asset: lib/fonts/tilda_sans/TildaSans-Light.ttf
          weight: 300
        - asset: lib/fonts/tilda_sans/TildaSans-Regular.ttf
          weight: 400
        - asset: lib/fonts/tilda_sans/TildaSans-Medium.ttf
          weight: 500
        - asset: lib/fonts/tilda_sans/TildaSans-Semibold.ttf
          weight: 600
        - asset: lib/fonts/tilda_sans/TildaSans-Bold.ttf
          weight: 700
        - asset: lib/fonts/tilda_sans/TildaSans-ExtraBold.ttf
          weight: 800
        - asset: lib/fonts/tilda_sans/TildaSans-Black.ttf
          weight: 900
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
